import "./index.css";
import "./auth.css";

// components
import Navbar from "@/components/navbar/Navbar";
import { AccountProvider } from "@/context/AccountContext";

export const metadata = {
  title: "Marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AccountProvider>
        <body>
          <Navbar />
          {children}
        </body>
      </AccountProvider>
    </html>
  );
}
