import "./index.css";
import "./auth.css";

// component & context
import { AccountProvider } from "@/context/AccountContext";
import Navbar from "@/components/navbar/Navbar";

export const metadata = {
  title: "Marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AccountProvider>
          {/* <Navbar /> */}
          {children}
        </AccountProvider>
      </body>
    </html>
  );
}
